# Generated by Django 5.0.6 on 2024-07-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_description_remove_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='phone',
            new_name='contact_number',
        ),
    ]
