# Generated by Django 5.0.6 on 2024-07-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
